### ISSUE TITLE
Error on startup with newest releases (NoSuchMethodError: 'com.sun.jna.Library com.sun.jna.Native.load)

### ISSUE THREAD

**Issue by sp3ctum** [Philippus/sbt-dotenv#81]
Hello, I'm trying this plugin out for my project at work. I'm getting this error with the latest release 
```
[error] java.lang.NoSuchMethodError: 'com.sun.jna.Library com.sun.jna.Native.load(java.lang.String, java.lang.Class)'
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```

Version 2.1.176 still works, but 2.1.184 onwards give me this error.

**Comment by sp3ctum** [comment]
With the working version 2.1.176 I'm able to load my .env file just fine, seems like that version can be used as a workaround.

**Comment by Philippus** [comment]
Native.load was introduced in https://github.com/mefellows/sbt-dotenv/pull/65. Are you maybe forcing an older version of jna? sbt-dotenv uses jna 5.6.

**Comment by sp3ctum** [comment]
Hmm not sure, might be possible as I'm not that familiar with my project yet.
Would you know of a way to check this?

**Comment by bluedigits** [comment]
Same problem here! With sbt `1.4.4` you at least can load the project but it gives you the illegal reflective access warning:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by au.com.onegeek.sbtdotenv.DirtyEnvironmentHack$ (file:/Users/merlin/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/au.com.onegeek/sbt-dotenv/scala_2.12/sbt_1.0/2.1.206/jars/sbt-dotenv.jar) to field java.lang.ProcessEnvironment.theEnvironment
WARNING: Please consider reporting this to the maintainers of au.com.onegeek.sbtdotenv.DirtyEnvironmentHack$
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by Philippus** [comment]
Are you on java 9+? https://github.com/mefellows/sbt-dotenv#illegal-reflective-access-warnings

**Comment by bluedigits** [comment]
> Are you maybe forcing an older version of jna? sbt-dotenv uses jna 5.6.

We have the same problem and we don't force any older jna version. We use Java 8.0.275

**Comment by bluedigits** [comment]
Note: With sbt `1.4.5` the problem disappears

**Comment by shawnk-agconn** [comment]
Problem disappeared for my from switching from sbt 1.3.8 to 1.3.10

**Comment by Philippus** [comment]
The next release will target sbt 1.3.9 as a minimum. In that release of sbt jna 5.5 got introduced, which is used transitively in sbt-dotenv. https://github.com/Philippus/sbt-dotenv/pull/134 adds a comment to this issue.
